# Generated by Django 6.0.2 on 2026-02-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sem',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='usn',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
